name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.2+2

environment:
  sdk: '>=3.1.0 <4.0.0'

flutter_native_splash:
  image: assets/common/launch.png
  color: "#000000"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

  fluro: ^2.0.5

  # 打印
  stack_trace:

  # 打开外部应用
  url_launcher: ^6.3.1

  #提示
  fluttertoast: ^8.2.12

  #播放视频
  video_player: ^2.10.0

  #加载本地文件
  path_provider: ^2.1.5

  #上拉下拉
  pull_to_refresh: ^2.0.0

  # loading
  flutter_easyloading: ^3.0.5

  # 蓝牙
  flutter_blue_plus: ^1.35.5

  #瀑布流
  flutter_staggered_grid_view: ^0.7.0

  #本地存储
  shared_preferences: ^2.5.3

  #版本号
  package_info_plus: ^8.3.0

  # logo
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  #闪屏
  flutter_native_splash:

  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true

  # 要为 Android 设单独图标：
  image_path_android: "assets/common/icon_logo_android.png"
  # 要为 iOS 设单独图标：
  image_path_ios: "assets/common/icon_logo_ios.png"
# dart run flutter_launcher_icons:main


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/home/
    - assets/common/
    - assets/set/
    - assets/faba/
    - assets/radio/
    - assets/speaker/
    - assets/play/
    - assets/rgb/

flutter_intl:
  enabled: true
